package com.ppossatto.chronos.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import io.swagger.v3.oas.models.tags.Tag;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Configuration class for OpenAPI documentation generated by springdoc.
 */
@Configuration
public class OpenApiConfig {

   /**
    * Bean definition for the OpenAPI documentation configuration.
    *
    * @return the configured OpenAPI bean.
    */
   @Bean
   public OpenAPI chronosOpenApi(){
      return new OpenAPI()
         .info(
            new Info()
               .title("Chronos API")
               .description("""
                  Chronos is an open-source, flexible appointment and scheduling management system designed to handle any type of appointment or meeting scenario.

                  ## Key Features

                  - **Generic & Flexible**: Suitable for medical consultations, business meetings, coaching sessions, or any appointment-based service
                  - **RESTful API**: Clean, intuitive REST endpoints following industry best practices
                  - **Status Management**: Track appointments through their lifecycle (scheduled, confirmed, completed, cancelled)
                  - **Soft Delete**: Maintain data integrity with logical deletion
                  - **Audit Trail**: Automatic tracking of creation and modification timestamps
                  - **UUID-based**: Secure, collision-resistant identifiers
                  """)
               .version("v0.0.1-SNAPSHOT")
               .license(new License()
                  .name("Apache 2.0 License")
                  .url("https://github.com/Paulo-Possatto/chronos/blob/main/LICENSE"))
         )
         .servers(
            List.of(
               new Server()
                  .url("http://localhost:8080")
                  .description("Local development server for testing new implementations")
            )
         )
         .tags(
            List.of(
               new Tag()
                  .name("Appointment")
                  .description("Endpoints related with appointments operations")
            )
         );
   }
}
